### ISSUE TITLE
xuanzai 该账户权限分配是否合理，既然没有权限还能看到左侧菜单

### ISSUE THREAD

**Issue by tianshaokai** [MikuBlog/xz-admin#3]
1. 没有权限用户应该看不到左侧菜单，
2.既然能看到左侧菜单，点击后直接跳转到登录页面了

**Comment by MikuBlog** [comment]
先回答你第一个问题：菜单是可以直接分配给角色的。只要分配了相应的菜单，拥有该角色的用户登录后就能看到对应的菜单。如果没有权限，访问对应页面的接口就会提示无法访问。

第二个问题：只有在没有登录的状态下访问菜单项才会重新跳转到登录页面。

**Comment by MikuBlog** [comment]
总而言之：菜单和权限是分开的

**Comment by tianshaokai** [comment]
谢谢，不过我使用xuanzai 这个账户，已经登录了，点击用户管理，提示不能访问，还是跳转到了登录

**Comment by MikuBlog** [comment]
xuanzai账号应该是没有权限修改自身的，你再尝试一遍

**Comment by tianshaokai** [comment]
1 又试了一次两次进入的页面不一样
2.我点击了用户，虽然弹出了 不允许访问，，但页面还是显示出来了信息，感觉不太友好，
3.不过我想 菜单和权限分开 不知道是不是好的方案

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/62293804-f5e70780-b49b-11e9-89f1-167e31eb987e.png)

我本地 总是无法启动，不知道哪错了，希望大佬帮忙看看

**Comment by MikuBlog** [comment]
好的   我把这个问题处理一下，在访问这个页面的时候可能还有其他操作。    现在，我们的设计就是角色为超集，分别关联菜单、权限、部门...     而菜单、权限、部门都是分开的。这里的报错参考最下面的已知问题列表，把对应位置的svg处理器删掉

**Comment by tianshaokai** [comment]
@MikuBlog  大佬 你说的删除 svg 处理器 是删除哪里啊，没看懂

**Comment by MikuBlog** [comment]
从nodule_modules->iviews->dist->iview.css     在这个文件里查找并删除svg相关的代码

**Comment by tianshaokai** [comment]
@MikuBlog 头疼，删除后还是无法运行成功

**Comment by MikuBlog** [comment]
@tianshaokai 你有通过npm安装再跑吗

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/62296591-f97d8d00-b4a1-11e9-80e2-614a4133f3d5.png)

肯定啊 执行了 npm install 安装了依赖包

日志总是报url-loader 错误

**Comment by MikuBlog** [comment]
尝试把这个字体文件删了

**Comment by MikuBlog** [comment]
或者重新下载项目安装看看，我这边下载安装后是能够直接跑起来的

**Comment by tianshaokai** [comment]
我试了多次依然 跑不起来

**Comment by tianshaokai** [comment]
搞不懂，我是mac 电脑，删除了你说的那些，一样跑不起来
