### ISSUE TITLE
线上接口部分404或者调用不同

### ISSUE THREAD

**Issue by alphagege** [MikuBlog/xz-admin#54]
您好，大佬。看了下感觉项目体验挺好的，准备学习一下，就是有点小问题，有的接口404
![image](https://user-images.githubusercontent.com/29486562/78235797-bd586b80-750b-11ea-9b4d-4e7f359cfd1a.png)

**Comment by MikuBlog** [comment]
线上的接口不公开的，该项目暂时只做展示使用。前端源码随意浏览。
